### ISSUE TITLE
Add pre-commit action to run interrogate

### ISSUE THREAD

**Issue by tchklovski** [predictionmachine/pm-github-actions#56]
I looked into it a bit and recommend adding the following config. in particular, 
        pass_filenames: false
is needed for some reason, as per https://github.com/econchick/interrogate/issues/60
```
  - repo: https://github.com/econchick/interrogate
    # cf http://www.pydocstyle.org/en/stable/index.html
    rev: 1.4.0
    hooks:
      - id: interrogate
        args: [ -vv, --config=pyproject.toml ]
        # see https://github.com/econchick/interrogate/issues/60
        pass_filenames: false
```
